KitapDostu/Models/Kitap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KitapDostu.Models
{
    public class Kitap
    {
        public int Kitapid { get; set; }
        [Required]
        [Display(Name ="Kitap Adı")]
        public string KitapAdi { get; set; }
        [Required]
        [Display(Name = "Sayfa Numarası")]
        public int Sayfa { get; set; }
        [Required]
        [Display(Name = "Yazar Adı")]
        public string Yazar { get; set; }
    }
}

KitapDostu/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KitapDostu.Models
{
    public class Kullanici
    {
        public int id { get; set; }
        [Display(Name ="Kullanıcı Adı")]
        [Required]
        public  string Ad { get; set; }
        [Display(Name = "Sifre")]
        [Required]
        public string Sifre { get; set; }
    }
}

KitapDostu/Models/Okuyan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KitapDostu.Models
{
    public class Okuyan
    {
        public int Okuyanid { get; set; }
        [Required]
        [Display(Name ="Adı")]
        public string OkuyanAd { get; set; }
        [Required]
        [Display(Name = "Soyadı")]
        public string  OkuyanSoyad { get; set; }

    }
}

KitapDostu/Areas/Admin/Controllers/GirisController.cs
using KitapDostu.DAL;
using KitapDostu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace KitapDostu.Areas.Admin.Controllers
{  [AllowAnonymous]
    public class GirisController : Controller
    {
        // GET: Admin/Giris
        KitapContext ctx = new KitapContext();

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Kullanici kullanici)
        {
            var kul = ctx.Kullanicilar.FirstOrDefault(x => x.Ad == kullanici.Ad && x.Sifre == kullanici.Sifre);
            if (kul != null)
            {
                FormsAuthentication.SetAuthCookie(kul.Ad, false);
                return RedirectToAction("Index", "Kitap");
            }
            else
            {
                return View("Index", "Kitap");
               
            }

        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return View("Login");
        }
    }
}

KitapDostu/Areas/Admin/Controllers/KitapController.cs
using KitapDostu.DAL;
using KitapDostu.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapDostu.Areas.Admin.Controllers
{
    public class KitapController : Controller
        
    {
        KitapContext ctx = new KitapContext();
        // GET: Admin/Kitap
        public ActionResult Index()

        {  
            
                var kitaplar = ctx.Kitaplar.ToList();
                return View(kitaplar);

            
           
        }

        public ActionResult KitapEkle()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(Kitap ktp)
        {

            if (ModelState.IsValid)
            {
                ctx.Kitaplar.Add(ktp);
           

            int sonuc = ctx.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("Index");
                }
            }
            return View();
        }

        public ActionResult KitapGuncelle(int? id, Kitap ktp)
        {

            var kitap = ctx.Kitaplar.Find(id);

            if (ModelState.IsValid)
            {
                ctx.Kitaplar.Add(ktp);
            }
            return View(kitap);
        }
        [HttpPost]
        public ActionResult KitapGuncelle(Kitap ktp)
        {
            if (ModelState.IsValid)
            {
                ctx.Entry(ktp).State = EntityState.Modified;
                int sonuc = ctx.SaveChanges();
                if (sonuc > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        public ActionResult KitapSil(int? id)
        {

            var ktp = ctx.Kitaplar.Find(id);
            ctx.Kitaplar.Remove(ktp);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

KitapDostu/Areas/Admin/Controllers/KulaniciController.cs
using KitapDostu.DAL;
using KitapDostu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapDostu.Areas.Admin.Controllers
{
    public class KulaniciController : Controller
    {
        // GET: Admin/Kulanici
        KitapContext ctx = new KitapContext();
        public ActionResult Kayit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Kayit(Kullanici klc)
        {
            if (ModelState.IsValid)
            {
                ctx.Kullanicilar.Add(klc);
            }

            int sonuc = ctx.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("Login", "Giris");
            }
            return View();
        }
    }
}

KitapDostu/Areas/Admin/Controllers/OkuyanController.cs
using KitapDostu.DAL;
using KitapDostu.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapDostu.Areas.Admin.Controllers
{
    public class OkuyanController : Controller
    {
        KitapContext ctx = new KitapContext();
        // GET: Admin/Kitap
        public ActionResult Index()

        {

            var okuyanlar = ctx.Okuyanlar.ToList();
            return View(okuyanlar);



        }

        public ActionResult OkuyanEkle()
        {

            return View();
        }
        [HttpPost]
        public ActionResult OkuyanEkle(Okuyan oky)
        {

            if (ModelState.IsValid)
            {
                ctx.Okuyanlar.Add(oky);
            }

            int sonuc = ctx.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult OkuyanGuncelle(int? id, Okuyan o)
        {

            var oky = ctx.Okuyanlar.Find(id);

            if (ModelState.IsValid)
            {
                ctx.Okuyanlar.Add(o);
            }
            return View(oky);
        }
        [HttpPost]
        public ActionResult OkuyanGuncelle(Okuyan oky)
        {
            ctx.Entry(oky).State = EntityState.Modified;
            int sonuc = ctx.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult OkuyanSil(int? id)
        {

            var oky = ctx.Okuyanlar.Find(id);
            ctx.Okuyanlar.Remove(oky);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

KitapDostu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapDostu.Controllers
{ [AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

KitapDostu/Areas/Admin/Views/Giris/Login.cshtml
@model KitapDostu.Models.Kullanici
@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<h2>Login</h2>
<div>
    @using (Html.BeginForm("Login", "Giris", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(o => o.Ad);
            @Html.TextBoxFor(o => o.Ad, new { @class = "form-control" })
            @Html.ValidationMessageFor(o => o.Ad)
        </div>
        <div class="form-group">
            @Html.LabelFor(o => o.Sifre);
            @Html.TextBoxFor(o => o.Sifre, new { @type="password",@class = "form-control" })
            @Html.ValidationMessageFor(o => o.Sifre)
        </div>
        <input type="submit" name="button" value="Giriş Yap" class="btn btn-danger" />

        @Html.ActionLink("Kayıt ol", "Kayit", "Kulanici")
    }
</div>

KitapDostu/Areas/Admin/Views/Kitap/Index.cshtml
@using KitapDostu.Models
@{
    ViewBag.Title = "Index";
}
@model IEnumerable<Kitap>
<h2>Kitap Listesi</h2>

<table class="table table-striped">

    <thead>
        <tr>
            <th>Kitap Adı</th>
            <th>Yazar Adı</th>
            <th>Sayfa Sayısı</th>
            <th>İşlemler</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.KitapAdi</td>
            <td>@item.Yazar</td>
            <td>@item.Sayfa</td>


            <td>

                <a href="/Admin/Kitap/KitapGuncelle/@item.Kitapid" class="btn btn-sm btn-primary">Guncelle</a>
                <a href="/Admin/Kitap/KitapSil/@item.Kitapid" class="btn btn-danger" onclick="return confirm('Bu kitabı silmek istediğinize emin misiniz?')">Sil</a>
            </td>
        </tr>
        }


    </tbody>

</table>

KitapDostu/Areas/Admin/Views/Kitap/KitapEkle.cshtml
@model KitapDostu.Models.Kitap

@{
    ViewBag.Title = "KitapEkle";
}

<h2>KitapEkle</h2>

@using (Html.BeginForm("KitapEkle", "Kitap", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(k => k.KitapAdi);
        @Html.TextBoxFor(k => k.KitapAdi, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KitapAdi)
        <label id="hataYzr" style="display:none;color:red">Yazar Adı Boş olamaz</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(k => k.Yazar);
        @Html.TextBoxFor(k => k.Yazar, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.Yazar)
        <label id="hataYzr" style="display:none;color:red">Yazar Adı Boş olamaz</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(k => k.Sayfa);
        @Html.TextBoxFor(k => k.Sayfa, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.Yazar)
        <label id="hataSyf" style="display:none;color:red">Sayfa Sayısı Boş olamaz</label>
    </div>
    <input type="submit" name="button" value="Kaydet" class="btn btn-danger" onclick="return BoslukKontrol()" />
}
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#KitapAdi").val() == "" || $("#Yazar").val() == "" || $("#Sayfa").val() == "") {
                $("#hataKtp").show();
                $("#hataYzr").show();
                $("#hataSyf").show();

                hatayok = false;
            }

            return hatayok;
        }

    </script>

}

KitapDostu/Areas/Admin/Views/Kitap/KitapGuncelle.cshtml
@model KitapDostu.Models.Kitap

@{
    ViewBag.Title = "KitapGuncelle";
}

<h2>KitapGuncelle</h2>

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{@Html.HiddenFor(k => k.Kitapid)
<div class="form-group">
    @Html.LabelFor(k => k.KitapAdi);
    @Html.TextBoxFor(k => k.KitapAdi, new { @class = "form-control" })
    <label id="hataKtp" style="display:none;color:red">Kitap Adı Boş olamaz</label>

</div>
<div class="form-group">
    @Html.LabelFor(k => k.Yazar);
    @Html.TextBoxFor(k => k.Yazar, new { @class = "form-control" })
    <label id="hataYzr" style="display:none;color:red">Yazar Adı Boş olamaz</label>

</div>
<div class="form-group">
    @Html.LabelFor(k => k.Sayfa);
    @Html.TextBoxFor(k => k.Sayfa, new { @class = "form-control" })
    <label id="hataSyf" style="display:none;color:red">Sayfa Sayısı Boş olamaz</label>

</div>
<input type="submit" name="button" value="Guncelle" class="btn btn-danger" onclick="return BoslukKontrol()"/>
}
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#KitapAdi").val() == "" || $("#Yazar").val() == "" || $("#Sayfa").val() == "") {
                $("#hataKtp").show();
                $("#hataYzr").show();
                $("#hataSyf").show();
               
                hatayok = false;
            }

            return hatayok;
        }

    </script>

}

KitapDostu/Areas/Admin/Views/Kulanici/Kayit.cshtml
@model KitapDostu.Models.Kullanici

@{
    ViewBag.Title = "Kayıt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kayıt</h2>

@using (Html.BeginForm("Kayit", "Kulanici", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(o => o.Ad);
        @Html.TextBoxFor(o => o.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Ad)
        <label id="lblAdHata" style="display:none;color:red">Ad alanı boş olamaz</label>

    </div>
    <div class="form-group">
        @Html.LabelFor(o => o.Sifre);
        @Html.TextBoxFor(o => o.Sifre, new { @type = "password", @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Sifre)
        <label id="lblHata" style="display:none;color:red">Şifre alanı boş olamaz</label>

    </div>
    <input type="submit" name="btnKaydet" value="Kaydol" class="btn btn-danger" onclick="return BoslukKontrol()" />

}

@section scripts{
    <script>
       function BoslukKontrol() {
           var hatayok = true;
           if ($("#Ad").val() == ""||$("#Sifre").val() == "") {
               $("#lblAdHata").show();
               $("#lblHata").show();
               hatayok = false;
           }

           return hatayok;
       }

    </script>

}

KitapDostu/Areas/Admin/Views/Okuyan/Index.cshtml
@using KitapDostu.Models
@{
    ViewBag.Title = "Okuyan Listesi";
}
@model IEnumerable<Okuyan>
<h2>Okuyucu Listesi</h2>

<table class="table table-striped">

    <thead>
        <tr>
            <th>Adı</th>
            <th>Soyadı</th>
            <th>İşlemler</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.OkuyanAd</td>
                <td>@item.OkuyanSoyad</td>
               


                <td>

                    <a href="/Admin/Okuyan/OkuyanGuncelle/@item.Okuyanid" class="btn btn-sm btn-primary">Guncelle</a>
                    <a href="/Admin/Okuyan/OkuyanSil/@item.Okuyanid" class="btn btn-danger" onclick="return confirm('Bu kişiyi silmek istediğinize emin misiniz?')">Sil</a>
                </td>
            </tr>
        }


    </tbody>

</table>

KitapDostu/Areas/Admin/Views/Okuyan/OkuyanEkle.cshtml
@model KitapDostu.Models.Okuyan

@{
    ViewBag.Title = "OkuyanEkle";
}

<h2>OkuyanEkle</h2>
@using (Html.BeginForm("OkuyanEkle", "Okuyan", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(o => o.OkuyanAd);
    @Html.TextBoxFor(o => o.OkuyanAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(o => o.OkuyanAd)
    <label id="hataAd" style="display:none;color:red">Ad alanı boş olamaz</label>
</div>
    <div class="form-group">
        @Html.LabelFor(o => o.OkuyanSoyad);
        @Html.TextBoxFor(o => o.OkuyanSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.OkuyanSoyad)
        <label id="hataSoyad" style="display:none;color:red">Soyad boş olamaz</label>
    </div>

    <input type="submit" name="button" value="Kaydet" class="btn btn-danger" />
     <label id="hataSoyad" style="display:none;color:red">Soyad boş olamaz</label>

}
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#OkuyanAd").val() == "" || $("#OkuyanSoyad").val() == "" ) {
                $("#hataSoyad").show();
                $("#hataAd").show();


                hatayok = false;
            }

            return hatayok;
        }

    </script>

}

KitapDostu/Areas/Admin/Views/Okuyan/OkuyanGuncelle.cshtml
@model KitapDostu.Models.Okuyan

@{
    ViewBag.Title = "OkuyanGuncelle";
}

<h2>OkuyanGuncelle</h2>

@using (Html.BeginForm("OkuyanGuncelle", "Okuyan", FormMethod.Post))
{@Html.HiddenFor(o => o.Okuyanid)
<div class="form-group">
    @Html.LabelFor(o => o.OkuyanAd);
    @Html.TextBoxFor(o => o.OkuyanAd, new { @class = "form-control" })
    <label id="hataAd" style="display:none;color:red">Ad alanı boş olamaz</label>

</div>
<div class="form-group">
    @Html.LabelFor(o => o.OkuyanSoyad);
    @Html.TextBoxFor(o => o.OkuyanSoyad, new { @class = "form-control" })
    <label id="hataSoyad" style="display:none;color:red">Soyad boş olamaz</label>

</div>
<input type="submit" name="button" value="Guncelle" class="btn btn-danger" onclick="return BoslukKontrol()" />
}
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#OkuyanAd").val() == "" || $("#OkuyanSoyad").val() == "" ) {
                $("#hataSoyad").show();
                $("#hataAd").show();
                

                hatayok = false;
            }

            return hatayok;
        }

    </script>

}

KitapDostu/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kitap Dostu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Admin/Kitap/KitapEkle"> Kitap Ekle</a></li>

                    <li><a href="/Admin/Kitap/Index"> Kitap Listesi</a></li>
                    <li><a href="/Admin/Okuyan/OkuyanEkle"> Okuyan Ekle</a></li>
                    <li><a href="/Admin/Okuyan/Index">  Okuyan Listele</a></li>
                    <li><a href="/Home/Contact"> Bize Ulaşın</a></li>
                    <li><a href="/Admin/Giris/Logout"> Çıkış Yap</a></li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", false)
</body>
</html>

KitapDostu/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>

<input type="email" name="mail" value="" placeholder="Email" />
@Html.TextArea("Iletisim")
<script type="text/javascript">
            var editor = CKEDITOR.instances['Iletisim'];
            if (editor) { editor.destroy(true); }
            CKEDITOR.replace('Iletisim', {
                enterMode: CKEDITOR.ENTER_BR,
            });
            CKFinder.setupCKEditor(null, '@Url.Content("~/ckeditor/ckfinder/")');
</script>
<input type="submit" name="btn" value="Gönder" />

KitapDostu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Kitap Dostu Uygulamasına Hoş Geldiniz</h2>

KitapDostu/Views/Shared/EditorTemplates/Html.cshtml
@Html.TextArea("", ViewData.TemplateInfo.FormattedModelValue.ToString(), new { @class = "ckeditor" })

KitapDostu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>